package gui;

import java.awt.Rectangle;


public class ChatClientGUI extends java.awt.Frame {

    /**
     * Creates new form Gui_Chat_Client
     */
    public ChatClientGUI(ChatClientGUIInterface guiInterface) {
        initComponents();
        this.guiInterface = guiInterface;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel1 = new java.awt.Panel();
        txtDialogPartner = new java.awt.Label();
        tbMessage = new java.awt.TextArea();
        btnSend = new java.awt.Button();
        lstAllReachables = new java.awt.List();
        tbChat = new java.awt.TextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panel1.setLayout(new java.awt.GridBagLayout());

        txtDialogPartner.setText("Dialog Partner");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel1.add(txtDialogPartner, gridBagConstraints);

        add(panel1, java.awt.BorderLayout.NORTH);
        add(tbMessage, java.awt.BorderLayout.SOUTH);

        btnSend.setActionCommand("btnSendActionCommand");
        btnSend.setLabel("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, java.awt.BorderLayout.EAST);

        lstAllReachables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstAllReachablesActionPerformed(evt);
            }
        });
        add(lstAllReachables, java.awt.BorderLayout.WEST);
        add(tbChat, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {                          
        System.exit(0);
    }                         

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	guiInterface.sendMessage(lstAllReachables.getSelectedItem(), tbMessage.getText());
    }                                       

    private void lstAllReachablesActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    // Variables declaration - do not modify
    private ChatClientGUIInterface guiInterface;
    private java.awt.Button btnSend;
    java.awt.List lstAllReachables;
    private java.awt.Panel panel1;
    java.awt.TextArea tbChat;
    java.awt.TextArea tbMessage;
    private java.awt.Label txtDialogPartner;
    // End of variables declaration
}
